import {
  PawPrint, Star, Sun, Heater, Waves, Sailboat, TreePine, MountainSnow, Tent,
  Wifi, Car, Flame, Coffee, Utensils, ShowerHead
} from "lucide-react"
import type { House } from "./types"

export const mockHouses: House[] = [
  {
    id: 1,
    name: "川西·森林秘境小屋",
    region: "四川·阿坝",
    lat: 31.8,
    lng: 103.5,
    available: 1,
    adults: 2,
    dogsAllowed: true,
    hasSauna: false,
    isLakeNearby: false,
    isSecluded: true,
    description: "坐落在川西高原的原始森林边缘，露台外即是壮丽山景，时有野生动物出没。体验远离尘嚣的宁静。",
    longDescription: "川西·森林秘境小屋坐落在海拔2800米的川西高原原始森林边缘，四周被参天古木和野花草甸环绕。这里是真正远离尘嚣的秘境——清晨，阳光穿过松林洒在露台上；夜晚，银河如瀑布般倾泻在头顶。小屋采用全球领先的零碳建筑技术，100%太阳能供电，雨水循环利用，让您在享受极致自然体验的同时，不给这片净土留下碳足迹。",
    scenery: ["森林", "高山", "僻静"],
    activities: ["徒步", "观星", "放松"],
    features: [
      { icon: PawPrint, text: "允许携带宠物" },
      { icon: TreePine, text: "深入自然" },
      { icon: Sun, text: "僻静之所" },
      { icon: Star, text: "冒险等级", level: 2 },
    ],
    travelTimes: [{ city: "成都", time: "约3.5小时车程" }],
    price: 1350,
    image: "/house1.avif",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    hostName: "林夕",
    hostDescription: "前生态学研究员，热爱户外运动和可持续生活。",
    gettingThere: "从成都出发，沿都汶高速转317国道，全程约280公里。建议自驾或包车前往。",
    exploreItems: [
      { title: "原始森林徒步", description: "穿越千年古木林，沿途可见珍稀植物和野生动物踪迹", image: "/house1.avif" },
      { title: "星空观测台", description: "海拔2800米的绝佳观星位置，银河清晰可见", image: "/house2.avif" },
      { title: "藏式早餐体验", description: "品尝地道酥油茶、糌粑和高原野菜", image: "/house3.avif" },
    ],
    faqs: [
      { question: "海拔高会不会有高反？", answer: "小屋海拔约2800米，大多数人不会有明显高反。建议到达当天充分休息，避免剧烈运动。我们备有氧气瓶以备不时之需。" },
      { question: "冬天可以入住吗？", answer: "全年可入住。冬季（11月-3月）会有积雪，我们提供地暖和壁炉，室内温暖舒适。冬季道路可能需要防滑链。" },
      { question: "有网络和手机信号吗？", answer: "小屋提供卫星Wi-Fi，可满足基本上网需求。移动信号较弱，建议提前告知亲友。" },
    ],
  },
  {
    id: 2,
    name: "洱海·湖光山色别墅",
    region: "云南·大理",
    lat: 25.7,
    lng: 100.1,
    available: 2,
    adults: 4,
    dogsAllowed: false,
    hasSauna: true,
    isLakeNearby: true,
    isSecluded: false,
    description: "直面洱海，全景落地窗将苍山洱海尽收眼底。配备私人桑拿房，享受极致的放松体验。",
    longDescription: "洱海·湖光山色别墅位于洱海东岸最佳观景带，270°全景落地窗将苍山十九峰和洱海碧波尽收眼底。清晨在湖面金光中醒来，傍晚在私人桑拿房中看落日余晖洒满苍山。别墅采用太阳能热水和地源热泵系统，实现全年零碳运营。",
    scenery: ["湖畔", "山景"],
    activities: ["环湖骑行", "皮划艇", "桑拿", "品茶"],
    features: [
      { icon: Waves, text: "一线湖景" },
      { icon: Heater, text: "配备桑拿" },
      { icon: Waves, text: "靠近水域" },
      { icon: Star, text: "冒险等级", level: 1 },
    ],
    travelTimes: [{ city: "大理古城", time: "约30分钟车程" }],
    price: 1800,
    image: "/house2.avif",
    checkInTime: "14:00",
    checkOutTime: "12:00",
    hostName: "云舒",
    hostDescription: "大理本地人，精通白族文化和茶道。",
    gettingThere: "从大理古城出发，沿环海东路向南，约30分钟到达。可安排接机服务。",
    exploreItems: [
      { title: "环洱海骑行", description: "沿着最美环海公路，感受风花雪月的诗意", image: "/house2.avif" },
      { title: "私人皮划艇", description: "在洱海上泛舟，近距离欣赏苍山倒影", image: "/house4.avif" },
      { title: "白族三道茶", description: "体验'一苦二甜三回味'的千年茶道", image: "/house5.avif" },
    ],
    faqs: [
      { question: "别墅距离洱海有多远？", answer: "步行仅需2分钟即可到达湖边，设有私人观景栈道。" },
      { question: "桑拿需要额外收费吗？", answer: "不需要，私人桑拿房包含在房费中，24小时可使用。" },
    ],
  },
  {
    id: 3,
    name: "内蒙·草原星空帐篷",
    region: "内蒙古·呼伦贝尔",
    lat: 49.2,
    lng: 119.7,
    available: 3,
    adults: 2,
    dogsAllowed: true,
    hasSauna: false,
    isLakeNearby: false,
    isSecluded: false,
    description: "豪华草原帐篷，夜晚可在私人露台上仰望璀璨星河。体验牧民生活，感受草原的辽阔与自由。",
    longDescription: "在呼伦贝尔大草原的腹地，我们搭建了这座融合现代舒适与草原文化的豪华帐篷营地。配备舒适的大床、独立卫浴和全景天窗——躺在床上就能仰望银河。白天骑马穿越草原，傍晚围着篝火听牧民唱长调，这是最真实的草原体验。",
    scenery: ["草原", "星空"],
    activities: ["骑马", "篝火晚会", "体验牧民生活"],
    features: [
      { icon: PawPrint, text: "允许携带宠物" },
      { icon: Tent, text: "特色帐篷体验" },
      { icon: Star, text: "冒险等级", level: 1 },
    ],
    travelTimes: [{ city: "海拉尔", time: "约2小时车程" }],
    price: 980,
    image: "/house3.avif",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    hostName: "巴特尔",
    hostDescription: "蒙古族牧民后代，精通马术和草原文化。",
    gettingThere: "从海拉尔东山机场出发，沿S201省道向北，约2小时到达营地。提供接机服务。",
    exploreItems: [
      { title: "草原骑马", description: "在专业牧民带领下，骑马穿越辽阔草原", image: "/house3.avif" },
      { title: "篝火晚会", description: "围坐篝火旁，品尝烤全羊，聆听草原长调", image: "/house1.avif" },
      { title: "牧民生活体验", description: "参与放牧、挤奶等传统牧民日常活动", image: "/house6.avif" },
    ],
    faqs: [
      { question: "帐篷里有卫生间吗？", answer: "每顶帐篷都配备独立卫浴，包括淋浴和卫生间，热水24小时供应。" },
      { question: "最佳游览季节是什么时候？", answer: "6-9月是草原最美的季节，草色青翠、野花遍地。7-8月还可以参加那达慕大会。" },
    ],
  },
  {
    id: 4,
    name: "长白山·林海雪原木屋",
    region: "吉林·长白山",
    lat: 42.5,
    lng: 128.0,
    available: 1,
    adults: 3,
    dogsAllowed: true,
    hasSauna: true,
    isLakeNearby: false,
    isSecluded: true,
    description: "隐藏在长白山深处的林海雪原中，冬季可体验滑雪乐趣。室内壁炉和桑拿带来温暖舒适。",
    longDescription: "林海雪原木屋坐落在长白山原始森林深处，冬天白雪皑皑如同童话世界，夏日绿荫环绕清凉宜人。木屋全部采用当地可持续采伐的落叶松建造，配备壁炉和芬兰桑拿房。距离长白山国际滑雪场仅15分钟车程，是冬季滑雪度假的绝佳选择。",
    scenery: ["森林", "雪山", "僻静"],
    activities: ["滑雪", "徒步雪林", "壁炉夜话", "桑拿"],
    features: [
      { icon: PawPrint, text: "允许携带宠物" },
      { icon: MountainSnow, text: "邻近雪场" },
      { icon: Heater, text: "配备桑拿" },
      { icon: Sun, text: "僻静之所" },
      { icon: Star, text: "冒险等级", level: 3 },
    ],
    travelTimes: [{ city: "长白山机场", time: "约1小时车程" }],
    price: 1600,
    image: "/house4.avif",
    checkInTime: "15:00",
    checkOutTime: "11:00",
    hostName: "林峰",
    hostDescription: "长白山护林员退休，对这片森林了如指掌。",
    gettingThere: "从长白山机场出发，沿抚长高速约1小时到达。冬季建议四驱车或安排接送。",
    exploreItems: [
      { title: "长白山滑雪", description: "距国际滑雪场仅15分钟，适合各级别滑雪者", image: "/house4.avif" },
      { title: "雪地温泉", description: "在零下20度的雪地中享受天然温泉", image: "/house2.avif" },
      { title: "森林雪橇", description: "乘坐狗拉雪橇穿越白桦林", image: "/house5.avif" },
    ],
    faqs: [
      { question: "冬天会很冷吗？", answer: "室外确实很冷（-20°C左右），但木屋配备地暖、壁炉和桑拿，室内温暖如春。我们还提供雪地装备租借。" },
      { question: "夏天可以来吗？", answer: "当然！夏天是避暑胜地，平均气温22°C左右，可以徒步、赏花、观瀑布。" },
    ],
  },
  {
    id: 5,
    name: "莫干山·竹海幽居",
    region: "浙江·湖州",
    lat: 30.6,
    lng: 119.8,
    available: 2,
    adults: 2,
    dogsAllowed: false,
    hasSauna: false,
    isLakeNearby: false,
    isSecluded: true,
    description: "隐于莫干山竹海深处的设计师小屋，极简风格与自然融为一体。适合寻求宁静和创作灵感的旅客。",
    longDescription: "莫干山·竹海幽居是一座由知名建筑师操刀设计的极简主义小屋，全部采用竹材和回收材料建造。隐于莫干山万亩竹海深处，推开窗就是满目翠竹。这里没有电视，只有书架、茶台和瑜伽垫——它是为寻求宁静和灵感的人而生的。",
    scenery: ["森林", "竹海", "僻静"],
    activities: ["徒步", "瑜伽冥想", "阅读"],
    features: [
      { icon: TreePine, text: "竹海环绕" },
      { icon: Sun, text: "僻静之所" },
      { icon: Star, text: "冒险等级", level: 1 },
    ],
    travelTimes: [{ city: "杭州", time: "约1.5小时车程" }],
    price: 1100,
    image: "/house5.avif",
    checkInTime: "14:00",
    checkOutTime: "12:00",
    hostName: "竹君",
    hostDescription: "室内设计师，热爱极简生活和茶道。",
    gettingThere: "从杭州出发，沿杭长高速转莫干山风景区方向，全程约90公里。",
    exploreItems: [
      { title: "竹林冥想", description: "在专业导师指导下，于竹海深处进行正念冥想", image: "/house5.avif" },
      { title: "手工竹艺", description: "跟当地匠人学习传统竹编手艺", image: "/house3.avif" },
      { title: "山间茶道", description: "采摘莫干山黄芽，体验从采茶到品茶的全过程", image: "/house6.avif" },
    ],
    faqs: [
      { question: "有Wi-Fi吗？", answer: "提供高速Wi-Fi。但我们鼓励您在入住期间尽量减少屏幕时间，享受与自然相处的时光。" },
      { question: "适合带小孩吗？", answer: "小屋设计偏向安静休闲，更适合成人。12岁以上的孩子可以入住。" },
    ],
  },
  {
    id: 6,
    name: "阳朔·漓江画境",
    region: "广西·桂林",
    lat: 24.7,
    lng: 110.4,
    available: 1,
    adults: 4,
    dogsAllowed: true,
    hasSauna: false,
    isLakeNearby: true,
    isSecluded: false,
    description: "坐落于漓江精华段，推窗即是喀斯特山水画卷。可在私人码头乘竹筏游览，或在露台品茗赏景。",
    longDescription: "阳朔·漓江画境位于漓江最精华的兴坪段，窗外就是闻名世界的喀斯特山水画卷——这里正是20元人民币背面的风景。别墅设有私人码头，可随时乘竹筏游览漓江。傍晚在露台上品茗，看渔火在江面上点点闪烁，是最诗意的体验。",
    scenery: ["河畔", "山景", "喀斯特地貌"],
    activities: ["竹筏漂流", "攀岩体验", "乡村骑行"],
    features: [
      { icon: PawPrint, text: "允许携带宠物" },
      { icon: Waves, text: "靠近水域" },
      { icon: Sailboat, text: "私人码头" },
      { icon: Star, text: "冒险等级", level: 2 },
    ],
    travelTimes: [{ city: "阳朔县城", time: "约20分钟车程" }],
    price: 1500,
    image: "/house6.avif",
    checkInTime: "14:00",
    checkOutTime: "11:00",
    hostName: "江帆",
    hostDescription: "阳朔当地向导，对漓江山水了如指掌。",
    gettingThere: "从桂林两江机场出发，沿高速约1.5小时到达阳朔，再沿漓江方向20分钟到达。",
    exploreItems: [
      { title: "竹筏漂流", description: "从私人码头出发，漂流漓江最美河段", image: "/house6.avif" },
      { title: "喀斯特攀岩", description: "在专业教练指导下，挑战石灰岩峭壁", image: "/house4.avif" },
      { title: "乡村骑行", description: "骑行穿越田园风光，探访古老村落", image: "/house1.avif" },
    ],
    faqs: [
      { question: "雨季会影响入住吗？", answer: "4-6月是雨季，漓江水位上涨但景色更美。竹筏体验可能会根据水位调整，但不影响入住。" },
      { question: "码头可以钓鱼吗？", answer: "可以！我们提供钓具，您可以在码头或竹筏上垂钓，享受渔翁之乐。" },
    ],
  },
]

export function getHouseById(id: number): House | undefined {
  return mockHouses.find((h) => h.id === id)
}

export const allRegions = Array.from(new Set(mockHouses.map((h) => h.region)))
